name: Test Project

on:
  push:
    branches:
      - master

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Static Code Analysis
        run: yarn lint
      - name: Unit Tests
        run: yarn test --silent
      - name: Know Githun event
        run: console.log(${{ github.event_name }})
      - name: Know branch name
        run: console.log(${{ context.payload.pull_request.head.ref }})
